[theme]
primaryColor = "#FFB22C"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"